name             'site'
maintainer       'John Levermore'
maintainer_email 'john.levermore@zhibek.com'
description      'Installs/Configures the tee-shop site'

version          '0.1.0'

depends 'openssl'
depends 'nginx'
depends 'mysql'
depends 'redis2'
depends 'php-fpm'
depends 'composer'
depends 'nodejs'
depends 'openjdk'
depends 'firefox'
depends 'xvfb'
